### ISSUE TITLE
Marked GFM extensions not supported

### ISSUE THREAD

**Issue by psyrendust** [alampros/Docter#10]
I'm having issues getting the [README.md](https://github.com/alampros/Docter/blob/master/README.md) from [Docter](https://github.com/alampros/Docter) to render correctly in [Marked.app](http://markedapp.com/). Fenced codeblocks, strickthru, syntax highlighting, auto-linking, and table support are not matching to the rendered output on GitHub for the same file. Please see the attached screenshot for results from [Marked.app](http://markedapp.com/) v1.4.1 (225).

![Screenshot_4_18_13_12_35_PM](https://f.cloud.github.com/assets/928502/398780/956cbe76-a85f-11e2-9395-eb90ee050227.png)

Here are the screenshots from my Marked.app preferences.

![image](https://f.cloud.github.com/assets/928502/398787/b60c73e2-a85f-11e2-9bb8-f80b6d393097.png)

![image](https://f.cloud.github.com/assets/928502/398790/bc3c63bc-a85f-11e2-807e-8ad693582e1d.png)

![image](https://f.cloud.github.com/assets/928502/398792/c41cae5c-a85f-11e2-93a4-c955c867012f.png)

![image](https://f.cloud.github.com/assets/928502/398794/c934f976-a85f-11e2-8e46-38790944597a.png)

**Comment by alampros** [comment]
Sorry for the long-delayed response - I haven't touched this project in ages (obviously) since Marked.app now supports all the GFM goodies by default.
