### ISSUE TITLE
Problems using docter in event.js

### ISSUE THREAD

**Issue by Saroupille** [alampros/Docter#21]
Hi,

To use gfm with markdown-mode in emacs I downloaded docter.

After having installed the gems redcarpet and pygments.rb , I try to use docter on small markdown file and I get this :

```bash
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn /usr/local/bin/gfm ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

```

I don't understand where the problem come from. I don't have any instance of docter that is started somewhere else.

**Comment by alampros** [comment]
I'm sorry - this project is no longer maintained. I would suggest looking at [marked](https://github.com/chjj/marked) for more up-to-date markdown processor in javascript.
